// GENERATED by scripts/generate-provider-contract-docs.mjs. Do not edit by hand.

export const generatedProviderContractStates = {
  "anthropic": "current",
  "cursor": "current",
  "gemini-cli": "current",
  "github-copilot": "current",
  "openai": "current",
} as const;
